#include "DIALOG.h"
extern GUI_CONST_STORAGE GUI_BITMAP bmThumbRight_30x30;
extern GUI_CONST_STORAGE GUI_BITMAP bmThumbLeft_30x30;
extern GUI_CONST_STORAGE GUI_BITMAP bmThumbDisabled_30x30; 
extern GUI_CONST_STORAGE GUI_BITMAP bmLeft_80x30;
extern GUI_CONST_STORAGE GUI_BITMAP bmRight_80x30;
extern GUI_CONST_STORAGE GUI_BITMAP bmDisabled_80x30;